server :
   port: 12345
   servlet:
      context-path: /micro-add-service-context
      
spring:
  application:
    name: micro-add-service
      
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         #defaultZone: http://localhost:1234/eureka
         #defaultZone: http://localhost:1234/micro-eureka-service-discovery/eureka
         #defaultZone: http://localhost:1234/micro-eureka-service-discovery/eureka #for non-docker
         defaultZone: http://docker-eureka-calculator-discovery:1234/micro-eureka-service-discovery/eureka #for docker
   instance:
      hostname: docker-add-service #localhost #-for non-docker
